# HW01

## 1. Импорт библиотеки NumPy

In [1]:
import numpy as np

## 2. Примеры создания массивов

### 2.1. Из обычных списков

In [17]:
# Создание массива из обычного списка
list_array = np.array([1, 2, 3, 4])
print("Массив из списка:", list_array)

# Создание массивов с помощью встроенных функций
zeros_array = np.zeros(5)
ones_array = np.ones((2, 3))
arange_array = np.arange(0, 10, 2)

print("zeros:", zeros_array)
print("ones:\n", ones_array)
print("arange:", arange_array)

Массив из списка: [1 2 3 4]
zeros: [0. 0. 0. 0. 0.]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]


In [3]:
# из двумерного списка
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Двумерный массив из двумерного списка: \n", b, "\nТип: ", type(b), "\nФорма: ", b.shape)

Двумерный массив из двумерного списка: 
 [[1 2 3 4]
 [5 6 7 8]] 
Тип:  <class 'numpy.ndarray'> 
Форма:  (2, 4)


2.2 Атрибуты массива — shape и dtype

In [18]:
arr = np.array([[1.0, 2.0], [3.0, 4.0]])
print("Массив:\n", arr)
print("Форма (shape):", arr.shape)
print("Тип данных (dtype):", arr.dtype)

Массив:
 [[1. 2.]
 [3. 4.]]
Форма (shape): (2, 2)
Тип данных (dtype): float64


## 3. Индексирование и срезы

In [14]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

# Индексирование
print("Элемент [0, 1]:", arr[0, 1])

# Срезы
print("Первая строка:", arr[0, :])
print("Первый столбец:", arr[:, 0])
print("Подмассив:", arr[0:2, 1:3])

# Булево индексирование
mask = arr > 30
print("Элементы > 30:", arr[mask])

Элемент [0, 1]: 20
Первая строка: [10 20 30]
Первый столбец: [10 40]
Подмассив: [[20 30]
 [50 60]]
Элементы > 30: [40 50 60]


**4. Векторные операции и базовые статистики**

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Поэлементные арифметические операции
print("Сложение:", a + b)
print("Умножение:", a * b)
print("Квадрат:", a ** 2)

# Статистические функции
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Среднее:", np.mean(arr))
print("Сумма:", np.sum(arr))
print("Минимум:", np.min(arr))
print("Максимум:", np.max(arr))
print("Стандартное отклонение:", np.std(arr))

# По осям
print("Среднее по строкам:", np.mean(arr, axis=1))
print("Сумма по столбцам:", np.sum(arr, axis=0))

Сложение: [5 7 9]
Умножение: [ 4 10 18]
Квадрат: [1 4 9]
Среднее: 3.5
Сумма: 21
Минимум: 1
Максимум: 6
Стандартное отклонение: 1.707825127659933
Среднее по строкам: [2. 5.]
Сумма по столбцам: [5 7 9]
